---
title: Yummy Theme
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Your Name
email: my_email_address@lalala.com
location: My location
company: MyCompany
company_url: my_company_website
github_url: my_github_url
description: description_of_your_web_site
favicon: favicon.png
repository: github_username/github_username.github.io
url: http://localhost:4000
gems:
- jekyll-paginate
- jekyll-geo-pattern
- rouge
- kramdown
- jekyll-github-metadata
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
source: "."
destination: "./_site"
quiet: false
kramdown:
  input: GFM
  enable_coderay: true
disque: my_disque_settings
paginate: 10
paginate_path: page:num
navs:
- href: "/"
  label: Home
- href: "/open-source"
  label: Open-Source
- href: "/blog"
  label: Blog
- href: "/bookmark"
  label: Bookmark
- href: "/about"
  label: About
side_bar_repo_limit: 5
analytics:
  provider: google
  google:
    tracking_id: tracking_id
skill_software_keywords:
- Java
- C
- C++
- Qt
- Python
- MySQL
- Oracle
- SQLite
- PL/SQL
- Design Patterns
skill_j2ee_keywords:
- Spring
- Struct
- Hibernet
- MyBatis
- JSP
skill_web_keywords:
- HTML
- CSS
- JS
- JQuery
- Ajax
- AngularJS
- NodeJS
- ExpressJS
- MongoDB
- Redis
- PHP
- Symfony
- Boostrap
skill_mobile_app_keywords:
- Android
- Sketch UI Desgin
